<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role' => 'superadmin',
                'username' => 'Gospel',
                'email' => 'gospel@iabcafrica.com',
                'phone_no' => NULL,
                'author' => 'Editor',
                'lastname' => 'Obi',
                'firstname' => 'Gospel',
                'othername' => 'Ozioma',
                'gender' => 'Male',
                'dob' => NULL,
                'country' => 'England',
                'about' => 'Obi Gospel Ozioma is a young African economic researcher with deep love for the African project and African businesses. His passion for this course is overwhelming as he has cut through ethnic cum religious barriers to create awareness on the need to empower the youths as employers of labour.

Over the years, Ozioma has consulted for many start-up businesses in Nigeria and is the founder of the Initiating African Businesses Concept (IABC) International - a firm dedicated to engineering and promoting the African industries. Through IABC Center for Business and Academic Research, he has trained scores of Nigerian students in different faculties and institutions to attain their desired academic/research goals and interests.

A Nigerian from the industrial town of Nnewi, Anambra State, his interest in African industries was spurred by his immediate environment. Having acquired local experience in the African industries blended with his academic resourcefulness and vibes, he has captured a lot about what it takes to create, sustain and develop the African businesses of tomorrow.


He is a Fellow of the Policy Analysis and Research Forum of the Department of Economics in Nnamdi Azikiwe University; where his research interests has earned him various awards and prices, including the Central Bank of Nigeria Abuja Facilitator\'s Discretion Price and the Sir Emeka Offor Foundation Scholarship Scheme Award, among others during his undergraduate years.


A blogger, motivational speaker, poet, academic researcher, online business columnist and SME promoter - Obi has featured in many seminars as a resource person and has attended renowned conferences. He has been engaging himself towards an African-driven global market with intense passion for entrepreneurship education.


Currently, he is working on setting up the Initiating African Business Institute to help re-awaken and resuscitate the African enterprise - thereby promoting and servicing the African industries.',
                'occupation' => '',
                'industry' => 'Leisure & Travel',
                'job_desc' => 'Founder of IABC Africa',
                'education' => NULL,
                'photo' => '1570345332.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fvnJbnNyccegIu7tfCw98epgboJ6.a2pgZgqFT.HjVU23ol0qVnwW',
                'remember_token' => 'Mkp8jedkqVBVDESUzMNRiGTSPF4TbAehpmVY2X8m5fR2d9y4YazotRKESDXR',
                'created_at' => '2019-06-26 00:05:13',
                'updated_at' => '2019-11-19 16:33:16',
            ),
            1 => 
            array (
                'id' => 2,
                'role' => 'admin',
                'username' => 'Yusuf',
                'email' => 'yusuf@lancetech.com',
                'phone_no' => NULL,
                'author' => 'Editor',
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$tKx83pTMY30K1mZGMpGHVeEgkfzM.zqszxUgESOpF811ZgM2JEROW',
                'remember_token' => NULL,
                'created_at' => '2019-07-07 19:36:05',
                'updated_at' => '2019-08-03 15:22:43',
            ),
            2 => 
            array (
                'id' => 3,
                'role' => 'member',
                'username' => 'Client',
                'email' => 'client@lancetech.com',
                'phone_no' => NULL,
                'author' => NULL,
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JuZEXnTIzl6AnrRZJMJjuOsfmelAI23xstBNF6fmdtVVFA3QxXeja',
                'remember_token' => NULL,
                'created_at' => '2019-08-03 08:39:12',
                'updated_at' => '2019-08-03 15:18:56',
            ),
            3 => 
            array (
                'id' => 4,
                'role' => 'member',
                'username' => 'Manager',
                'email' => 'manager@lancetech.com',
                'phone_no' => NULL,
                'author' => NULL,
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1puWX6WtCt8DV./7nAwLkeIxtnc0Jd1yCmk2Ycqe/49uHTsNA8txW',
                'remember_token' => NULL,
                'created_at' => '2019-08-03 08:43:41',
                'updated_at' => '2019-08-03 08:43:41',
            ),
            4 => 
            array (
                'id' => 5,
                'role' => 'member',
                'username' => 'Founder',
                'email' => 'founder@lancetech.com',
                'phone_no' => NULL,
                'author' => 'Freelancer',
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Kb.NNI.pST.bKDHBUejW0.jHuZJrCJ2C5YEQIFoXWm8f/OJlnJh5W',
                'remember_token' => NULL,
                'created_at' => '2019-08-03 08:44:39',
                'updated_at' => '2019-08-03 15:18:44',
            ),
            5 => 
            array (
                'id' => 6,
                'role' => 'member',
                'username' => 'New',
                'email' => 'newest@lancetech.com',
                'phone_no' => NULL,
                'author' => 'Guest Writer',
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$EvoforTjEZxcRrPwEwEIg.asrbLT2LcaBQJ6QaBBXMGvKbNEFmkvC',
                'remember_token' => NULL,
                'created_at' => '2019-08-03 15:20:31',
                'updated_at' => '2019-08-03 15:21:07',
            ),
            6 => 
            array (
                'id' => 7,
                'role' => 'member',
                'username' => 'Welcome',
                'email' => 'welcome@lancetech.com',
                'phone_no' => NULL,
                'author' => NULL,
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cJsiVoympoWdBDiAfmvfze8pjAN2104yo/KppG6f.oFedJbIFWHtW',
                'remember_token' => NULL,
                'created_at' => '2019-08-04 09:42:12',
                'updated_at' => '2019-08-04 09:42:12',
            ),
            7 => 
            array (
                'id' => 8,
                'role' => 'member',
                'username' => 'Global',
                'email' => 'global@lancetech.com',
                'phone_no' => NULL,
                'author' => NULL,
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => 'Co-founder of IABC Africa',
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CwLV4./ZM.riMjs5FPW4e.NUjVTO6bQVMc6F7E6UAfuAjXcAQT.Ui',
                'remember_token' => NULL,
                'created_at' => '2019-08-04 09:43:58',
                'updated_at' => '2019-10-01 00:46:35',
            ),
            8 => 
            array (
                'id' => 9,
                'role' => 'member',
                'username' => 'Yusuf_Lateef',
                'email' => 'yusufomotoyosi@gmail.com',
                'phone_no' => NULL,
                'author' => NULL,
                'lastname' => NULL,
                'firstname' => NULL,
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CmhnXnbqYSV5K0UZaXAa.eKAe7ftzlgTu9.VOCgP39CKL/5HmLDhC',
                'remember_token' => NULL,
                'created_at' => '2019-09-06 05:54:42',
                'updated_at' => '2019-09-06 05:54:42',
            ),
            9 => 
            array (
                'id' => 10,
                'role' => 'member',
                'username' => 'Sandra_Anezu_827fb',
                'email' => 'sanezu@gmail.com',
                'phone_no' => NULL,
                'author' => 'Contributor',
                'lastname' => 'Sandra',
                'firstname' => 'Anezu',
                'othername' => NULL,
                'gender' => 'Female',
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => '1570016958.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NdyRlLlKZr5JL34sRtVgiu/teH44ctkHeJqBeWvFtC1I3iq8f7Sfu',
                'remember_token' => NULL,
                'created_at' => '2019-10-02 11:43:43',
                'updated_at' => '2019-10-02 13:19:05',
            ),
            10 => 
            array (
                'id' => 11,
                'role' => 'admin',
                'username' => 'IABC Africa_Media_baf45',
                'email' => 'officialiabcafrica@gmail.com',
                'phone_no' => NULL,
                'author' => 'Contributor',
                'lastname' => 'IABC Africa',
                'firstname' => 'Media',
                'othername' => NULL,
                'gender' => 'Rather not Say',
                'dob' => NULL,
                'country' => NULL,
                'about' => 'This is the official Media channel of IABC Africa handled by the IABC Africa Team.',
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => 'The Media Department of IABC Africa',
                'education' => NULL,
                'photo' => '1570354778.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$de8uk.XQk.FR.aL0L7BYG.HAY92UgctnO6I8uB4MSdrDjl1U12Qve',
                'remember_token' => NULL,
                'created_at' => '2019-10-02 14:07:41',
                'updated_at' => '2019-11-19 13:22:16',
            ),
            11 => 
            array (
                'id' => 12,
                'role' => 'member',
                'username' => 'nLtwuDPVxpsNqBUl',
                'email' => 'maryharris5605@gmail.com',
                'phone_no' => NULL,
                'author' => NULL,
                'lastname' => 'cVropnQStdOx',
                'firstname' => 'cjULvQSG',
                'othername' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'country' => NULL,
                'about' => NULL,
                'occupation' => NULL,
                'industry' => NULL,
                'job_desc' => NULL,
                'education' => NULL,
                'photo' => 'head.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3NnrPk6fvYLj9cmu6yiudO3GStWKy/3MlyC0BaUVlEl17.jpF8BVi',
                'remember_token' => NULL,
                'created_at' => '2019-12-21 12:04:02',
                'updated_at' => '2019-12-21 12:04:02',
            ),
        ));
        
        
    }
}