<option value="">Industry</option>
<option value="Architecture & Planning">Architecture & Planning</option>
<option value="Arts & Crafts">Arts & Crafts</option>
<option value="Automotive">Automotive</option>
<option value="Aviation & Aerospace">Aviation & Aerospace</option>
<option value="Banking">Banking</option>
<option value="Biotechnology">Biotechnology</option>
<option value="Broadcast Media">Broadcast Media</option>
<option value="Building Materials">Building Materials</option>
<option value="Business Supplies & Equipment">Business Supplies & Equipment</option>
<option value="Capital Markets">Capital Markets</option>
<option value="Chemicals">Chemicals</option>
<option value="Civil & Social Organization">Civil & Social Organization</option>
<option value="Civil Engineering">Civil Engineering</option>
<option value="Commercial Real Estate">Commercial Real Estate</option>
<option value="Computer & Network Security">Computer & Network Security</option>
<option value="Computer Games">Computer Games</option>
<option value="Computer Hardware">Computer Hardware</option>
<option value="Computer Networking">Computer Networking</option>
<option value="Cosmetics">Cosmetics</option>
<option value="Dairy">Dairy</option>
<option value="Defense & Space">Defense & Space</option>
<option value="Design">Design</option>
<option value="Education Management">Education Management</option>
<option value="E-learning">E-learning</option>
<option value="Electrical & Electronic Manufacturing">Electrical & Electronic Manufacturing</option>
<option value="Entertainment">Entertainment</option>
<option value="Environmental Services">Environmental Services</option>
<option value="Events Services">Events Services</option>
<option value="Executive Office">Executive Office</option>
<option value="Facilities Services">Facilities Services</option>
<option value="Farming">Farming</option>
<option value="Fundraising">Fundraising</option>
<option value="Furniture">Furniture</option>
<option value="Gambling & Casinos">Gambling & Casinos</option>
<option value="Glass">Glass</option>
<option value="Government Administration">Government Administration</option>
<option value="Government Relations">Government Relations</option>
<option value="Graphic Design">Graphic Design</option>
<option value="Health">Health</option>
<option value="Higher Education">Higher Education</option>
<option value="Hospital & Health Care">Hospital & Health Care</option>
<option value="Hospitality">Hospitality</option>
<option value="Human Resources">Human Resources</option>
<option value="Import & Export">Import & Export</option>
<option value="Investment Management">Investment Management</option>
<option value="Judiciary">Judiciary</option>
<option value="Law Enforcement">Law Enforcement</option>
<option value="Law Practice">Law Practice</option>
<option value="Legal Services">Legal Services</option>
<option value="Legislative Office">Legislative Office</option>
<option value="Leisure & Travel">Leisure & Travel</option>
<option value="Maritime">Maritime</option>
<option value="Marketing & Advertising">Marketing & Advertising</option>
<option value="Market Research">Market Research</option>
<option value="Mechanical/Industrial Engineering">Mechanical/Industrial Engineering</option>
<option value="Media Production">Media Production</option>
<option value="Medical Device">Medical Device</option>
<option value="Medical Practice">Medical Practice</option>
<option value="Mental Health Care">Mental Health Care</option>
<option value="Military">Military</option>
<option value="Mining & Materials">Mining & Materials</option>
<option value="Motion Pictures & Film">Motion Pictures & Film</option>
<option value="Museums & Institutions">Museums & Institutions</option>
<option value="Music">Music</option>
<option value="Nanotechnology">Nanotechnology</option>
<option value="Newspapers">Newspapers</option>
<option value="Nonprofit Organization Management">Nonprofit Organization Management</option>
<option value="Oil & Energy">Oil & Energy</option>
<option value="Online Publishing">Online Publishing</option>
<option value="Performing Arts">Performing Arts</option>
<option value="Pharmaceuticals">Pharmaceuticals</option>
<option value="Philanthropy">Philanthropy</option>
<option value="Photography">Photography</option>
<option value="Plastics">Plastics</option>
<option value="Political Organization">Political Organization</option>